INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('1','ALEMANIA','A','3','1')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('2','ARGELIA','A','4','2')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('3','ARGENTINA','A','1','3')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('4','AUSTRALIA','A','7','4')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('5','AUSTRIA','A','3','5')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('6','BÉLGICA','A','3','6')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('7','BOLIVIA','A','1','7')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('8','BRASIL','A','1','8')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('9','BULGARIA','A','3','9')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('10','CANADÁ','A','2','10')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('11','COLOMBIA','A','1','11')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('12','COREA','A','6','12')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('13','COSTA RICA','A','5','13')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('14','CUBA','A','5','14')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('15','CHILE','A','1','15')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('16','CHINA','A','6','16')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('17','DINAMARCA','A','3','17')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('18','ECUADOR','A','1','18')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('19','ESTADOS UNIDOS','A','2','19')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('20','EGIPTO','A','4','20')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('21','EL SALVADOR','A','5','21')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('22','ESPAÑA','A','3','22')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('23','FINLANDIA','A','3','23')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('24','FILIPINAS','A','6','24')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('25','FRANCIA','A','3','25')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('26','GRAN BRETAÑA','A','3','26')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('27','GRECIA','A','3','27')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('28','GUATEMALA','A','5','28')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('29','HOLANDA','A','3','29')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('30','HONDURAS','A','5','30')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('31','HUNGRÍA','A','3','31')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('32','INDIA','A','6','32')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('33','INDONESIA','A','6','33')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('34','ITALIA','A','3','34')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('35','ISRAEL','A','6','35')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('36','JAMAICA','A','3','36')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('37','JAPÓN','A','6','37')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('38','MALASIA','A','3','38')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('39','MARRUECOS','A','3','39')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('40','MÉXICO','A','3','40')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('41','NICARAGUA','A','3','41')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('42','NUEVA ZELANDIA','A','7','42')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('43','PANAMÁ','A','3','43')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('44','PARAGUAY','A','1','44')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('45','POLONIA','A','3','45')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('46','PORTUGAL','A','3','46')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('47','REPÚBLICA CHECA','A','3','47')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('48','REPÚBLICA DOMINICANA','A','5','48')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('49','RUMANÍA','A','6','49')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('50','RUSIA','A','6','50')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('51','SANTA SEDE','A','6','51')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('52','SERVIA Y MONTENEGRO','A','6','52')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('53','SINGAPUR','A','6','53')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('54','SUDÁFRICA','A','4','54')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('55','SUECIA','A','3','55')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('56','SUIZA','A','3','56')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('57','TAILANDIA','A','6','57')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('58','UCRANIA','A','3','58')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('59','URUGUAY','A','1','59')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('60','VENEZUELA','A','1','60')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('61','EMBAJADA DEL PERU EN LA REPUBLICA DE SUDAFRICA','A','4','61')
INSERT SAET_PAIS(pais_icodigo_pais,pais_vnombre_pais,pais_cestado,regi_icodigo_region,pais_vcodigo_pais) VALUES('62','PERU','A','1','62')